### ISSUE TITLE
Doppelpunkt vorm Text

### ISSUE THREAD

**Issue by exscorp** [heimseiten/contao-timeline-bundle#1]
Hallo Niels, durch die letzte Änderung erscheint vor dem Text jetzt ein "Doppelpunkt". 

![Screenshot 2021-06-16 103109](https://user-images.githubusercontent.com/3008649/122187554-6bd99980-ce8f-11eb-9cdb-b559818d86e9.jpg)

![Screenshot 2021-06-16 103831](https://user-images.githubusercontent.com/3008649/122187561-6da35d00-ce8f-11eb-9ea8-e6b9ea9c35ca.jpg)

Hat es ein technischen Sinn? Es ist auch hartkodiert und kann im Template nicht entfernen werden.

https://github.com/heimseiten/contao-timeline-bundle/blob/4a823203fce61011007629e6bc9b39f484360856/src/Controller/ContentElement/TimelineElementController.php#L37

**Comment by heimseiten** [comment]
Sorry, wurde in Version 1.0.12 korrigiert.

**Comment by exscorp** [comment]
danke
