### ISSUE TITLE
inviewport css

### ISSUE THREAD

**Issue by exscorp** [heimseiten/contao-timeline-bundle#2]
Das **inviewport.scss.css** wird auf jeder Seite geladen obwohl keine Timeline eingebunden ist.

Seite ohne Timeline:

![seite-ohne-timeline](https://user-images.githubusercontent.com/3008649/122192533-09cf6300-ce94-11eb-85f2-23bd00cac2c6.jpg)

Seite mit Timeline:

![seite-mit-timeline](https://user-images.githubusercontent.com/3008649/122192544-0cca5380-ce94-11eb-81d3-087184635abe.jpg)

**Comment by heimseiten** [comment]
Sorry, wurde mit der inviewport Version 1.0.7 korrigiert.

**Comment by exscorp** [comment]
danke für den schnellen fix

**Comment by heimseiten** [comment]
gerne!
